### ISSUE TITLE
EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by TheFonsi** [Niketion/PetFaction#1]
When I attack a entity at server version 1.12.1 ` Could not pass event EntityDamageByEntityEvent to PetFaction v1.4.4.5
org.bukkit.event.EventException: null
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-edd0396-2a927e8]
>       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-edd0396-2a927e8]
>       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:92) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:579) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:482) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:611) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1339) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:863) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1610) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at de.robingrether.idisguise.management.channel.InjectedPlayerConnection1121.a(InjectedPlayerConnection1121.java:63) [iDisguise.jar:?]
>       at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
>       at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-edd0396-2a927e8]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.Factions.getInstance()Lcom/massivecraft/factions/Factions;
>       at github.niketion.petfaction.listener.ListenerPetFaction.onEntityDamageByEntity(ListenerPetFaction.java:114) ~[?:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-edd0396-2a927e8]
>       ... 26 more
`

**Comment by Niketion** [comment]
The plugin cannot find faction.
Disable the depend on config.yml

**Comment by TheFonsi** [comment]
But I using latest factions plugin.
